### ISSUE TITLE
RMQ input error points to localhost when remote host is specified

### ISSUE THREAD

**Issue by JeMunos** [logstash-plugins/logstash-mixin-rabbitmq_connection#52]
when connecting to a remote RMQ server for input data, if the connection fails the error points to localhost:5671 even though the remote host may be totally different. 
```
[2018-06-19T16:59:26,078][ERROR][logstash.inputs.rabbitmq ] RabbitMQ connection error, will retry. {:error_message=>"Connection to localhost:5671 refused", :exception=>"MarchHare::ConnectionRefused", :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/march_hare-3.1.1-java/lib/march_hare/session.rb:505:in `converting_rjc_exceptions_to_ruby'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/march_hare-3.1.1-java/lib/march_hare/session.rb:541:in `new_connection_impl'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/march_hare-3.1.1-java/lib/march_hare/session.rb:534:in `build_new_connection'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/march_hare-3.1.1-java/lib/march_hare/session.rb:157:in `initialize'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/march_hare-3.1.1-java/lib/march_hare/session.rb:127:in `connect'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/march_hare-3.1.1-java/lib/march_hare.rb:24:in `connect'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-mixin-rabbitmq_connection-5.0.2-java/lib/logstash/plugin_mixins/rabbitmq_connection.rb:201:in `connect'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-mixin-rabbitmq_connection-5.0.2-java/lib/logstash/plugin_mixins/rabbitmq_connection.rb:138:in `connect!'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-rabbitmq-6.0.3/lib/logstash/inputs/rabbitmq.rb:183:in `setup!'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-rabbitmq-6.0.3/lib/logstash/inputs/rabbitmq.rb:177:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:512:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:505:in `block in start_input'"]}
[2018-06-19T16:59:26,955][DEBUG][logstash.config.source.multilocal] Reading pipeline configurations from YAML {:location=>"/etc/logstash/pipelines.yml"}
[2018-06-19T16:59:26,958][DEBUG][logstash.config.source.local.configpathloader] Skipping the following files while reading config since they don't match the specified glob pattern {:files=>[]}
[2018-06-19T16:59:26,959][DEBUG][logstash.config.source.local.configpathloader] Reading config file {:config_file=>"/etc/logstash/conf.d/test.conf"}
[2018-06-19T16:59:26,960][DEBUG][logstash.agent           ] Converging pipelines state {:actions_count=>0}
[2018-06-19T16:59:27,083][DEBUG][logstash.inputs.rabbitmq ] Connecting to RabbitMQ. Settings: {:vhost=>"/", :hosts=>["export-streaming.com"], :port=>443, :user=>"<UN>", :automatic_recovery=>true, :pass=>"<PW>", :timeout=>0, :heartbeat=>30, :tls=>"TLSv1.2", :tls_certificate_path=>nil, :tls_certificate_password=>nil}
[2018-06-19T16:59:27,085][WARN ][com.rabbitmq.client.TrustEverythingTrustManager] This trust manager trusts every certificate, effectively disabling peer verification. This is convenient for local development but prone to man-in-the-middle attacks. Please see http://www.rabbitmq.com/ssl.html#validating-cerficates to learn more about peer certificate validation.

```

**Comment by dbason** [comment]
We also experienced this issue after upgrading to 6.3.1.  I did some further testing and the issue occurs when use use the port configuration in the rabbitmq plugins.  If you remove that configuration then it uses the server configuration provided.  If you try and override the default port then it will try to connect to localhost:5671 no matter what the provided configuration is.

**Comment by dbason** [comment]
We are also experiencing this issue using the rabbitmq output plugin.

It seems to be specific to Centos7.  This issue doesn't occur on Centos6

**Comment by neilc2016** [comment]
I am having this issue when upgrading logstash from 6.2.2 to 6.4.1 on Redhat 7.  Is there any resolution?

**Comment by neilc2016** [comment]
I found a workaround.  If the port is specified in the host configuration like below the logstash agent connects to rabbitmq correctly.

rabbitmq {
host => "ves-elkmq-test.ebiz.verizon.com:35672"
vhost => "vapews"
exchange => "vapews_exchange"
queue => "vapews_queue"
key => "vapews_key"
user => "vapews"
password => "xxxxxx"
ack => false
threads => 1
durable => true
#port => 35672
ssl => true
ssl_version => "TLSv1.2"
}

**Comment by keitalbame** [comment]
Having the same issue with the container `docker.elastic.co/logstash/logstash:6.6.2` when setting up TLS. Without TLS everything works fine.
Applying the workaround mentioned by @neilc2016 did not helped because if no port is setup, it will default to 5672.

```
logstash_1  | [2019-03-29T11:27:17,422][DEBUG][logstash.outputs.rabbitmq] Connecting to RabbitMQ. Settings: {:vhost=>"/", :hosts=>["rabbitmq:5671"], :port=>5672, :user=>"xxx", :automatic_recovery=>true, :pass=>"xxx", :timeout=>0, :heartbeat=>0, :tls=>"TLSv1.2", :tls_certificate_path=>xxx, :tls_certificate_password=>xxx}
logstash_1  | Using TLS/SSL version TLSv1.2
logstash_1  | [2019-03-29T11:27:17,422][WARN ][com.rabbitmq.client.TrustEverythingTrustManager] This trust manager trusts every certificate, effectively disabling peer verification. This is convenient for local development but prone to man-in-the-middle attacks. Please see http://www.rabbitmq.com/ssl.html#validating-cerficates to learn more about peer certificate validation.
logstash_1  | [2019-03-29T11:27:17,426][ERROR][logstash.outputs.rabbitmq] RabbitMQ connection error, will retry. {:error_message=>"Connection to localhost:5671 failed", :exception=>"MarchHare::ConnectionRefused", :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/march_hare-3.1.1-java/lib/march_hare/session.rb:511:in `converting_rjc_exceptions_to_ruby'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/march_hare-3.1.1-java/lib/march_hare/session.rb:541:in `new_connection_impl'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/march_hare-3.1.1-java/lib/march_hare/session.rb:534:in `build_new_connection'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/march_hare-3.1.1-java/lib/march_hare/session.rb:157:in `initialize'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/march_hare-3.1.1-java/lib/march_hare/session.rb:127:in `connect'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/march_hare-3.1.1-java/lib/march_hare.rb:24:in `connect'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-mixin-rabbitmq_connection-5.0.2-java/lib/logstash/plugin_mixins/rabbitmq_connection.rb:201:in `connect'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-mixin-rabbitmq_connection-5.0.2-java/lib/logstash/plugin_mixins/rabbitmq_connection.rb:138:in `connect!'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-rabbitmq-5.1.1-java/lib/logstash/outputs/rabbitmq.rb:47:in `register'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:102:in `register'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:46:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:259:in `register_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:270:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:270:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:611:in `maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:280:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:217:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:176:in `block in start'"]}
```
Keeping `port => 5671` also does not help solving the localhost issue.

Possibly related with https://github.com/ruby-amqp/march_hare/issues/133

**Comment by ymougenel** [comment]
Hello, :relaxed: 
If it is ok with you, I can upgrade the march dependency ([4.1.0](https://github.com/ruby-amqp/march_hare/blob/master/ChangeLog.md#corrected-log-messages-on-connection-failure) fixes the output) and test it with my local  set up?

**Comment by vurso** [comment]
I have this issue with the following setup:

docker ELK+RabbitMQ stack
Windows 10 Pro 16GB ram
vmem fix applied to both docker-desktop and the WSL 2 Ubuntu distro

Have tried various ports, changed the hostname but that didn't help the other containers spin up fine I can view Kibana and get to the RMQ management interface.

My logstash.conf:

`input {
	tcp {
		port => 5000
	}
	rabbitmq {
        host => "rabbit"
        port => 5672
        queue => "my-test-queue-001"
        durable => true
        passive => true
        exchange => "amq.default"
        user => "testuser001"
        password => "s0merandomP@ss"
    }
    beats {
        port => "5044"
    }
}

output {
	elasticsearch {
		hosts => "elasticsearch:9200"
	}
}`

Thanks in advance.

**Comment by vurso** [comment]
> I have this issue with the following setup:
> 
> docker ELK+RabbitMQ stack
> Windows 10 Pro 16GB ram
> vmem fix applied to both docker-desktop and the WSL 2 Ubuntu distro
> 
> Have tried various ports, changed the hostname but that didn't help the other containers spin up fine I can view Kibana and get to the RMQ management interface.
> 
> My logstash.conf:
> 
> `input {
> tcp {
> port => 5000
> }
> rabbitmq {
> host => "rabbit"
> port => 5672
> queue => "my-test-queue-001"
> durable => true
> passive => true
> exchange => "amq.default"
> user => "testuser001"
> password => "s0merandomP@ss"
> }
> beats {
> port => "5044"
> }
> }
> 
> output {
> elasticsearch {
> hosts => "elasticsearch:9200"
> }
> }`
> 
> Thanks in advance.

Hey folks I found that changing the port for RMQ to say 5674 works even though the log out will say connection refused just ignore it, daft I know but it get me past this problem (see ref: https://gitmemory.com/issue/logstash-plugins/logstash-output-rabbitmq/76/456807342)

**Comment by quarky42** [comment]
I see this same problem in Logstash 9.0.7 and 9.4.1.

Logstash is connecting to "rabbitmq.something.com"  (another docker container with that hostname) in docker swarm.
The log shows:
`Connected to RabbitMQ {url: "amqps://guest:XXXXXX@localhost:5671/"}`

If I set LOG_LEVEL=debug all of a sudden the log shows this instead:
`Connected to RabbitMQ {url: "amqps://guest:XXXXXX@rabbitmq.something.com:5671/"}`

I have host set to rabbitmq.something.com and port set to 5671.    The other issue here is that when LOG_LEVEL=debug I am getting data into elastisearch successfully.  With LOG_LEVEL=info logstash is not able to initialize successfully.

I have a bunch of rabbitmq inputs defined.   Running on the latest version of Docker CE on Oracle Linux 9 with selinux enforcement enabled on OL9 and selinux flag enabled within Docker CE.

I started seeing problems with rabbitmq data not being sent to elasticsearch by logstash as soon as Docker CE was upgraded and selinux flag was enabled.   It has been working perfectly on the system prior to that where selinux enforcement was on, but docker itself was blissfully unaware of it.

I likely will need to report a new bug, but it sure seems like it is related to this old one as well.
